name: ApiTest
on: push
jobs:
  build:
    runs-on: windows-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Setup Java JDK
        uses: actions/setup-java@v4.6.0
        with:
          java-version: 22
          distribution: zulu
        
      - name: Set up Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1  # Используем Gradle Wrapper для проекта

  test_register_user_positive:
    runs-on: ubuntu-latest
    needs: build     
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Setup Java JDK
        uses: actions/setup-java@v4.6.0
        with:
          java-version: 22
          distribution: zulu
          
      - name: Set execute permissions on gradlew
        run: chmod +x ./gradlew
          
      - name: Run Register User Positive Test
        run: ./gradlew test --tests ApiTest#positiveTestRegisterUser

  test_register_user_negative_without_password:
    runs-on: ubuntu-latest
    needs: build     
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Setup Java JDK
        uses: actions/setup-java@v4.6.0
        with:
          java-version: 22
          distribution: zulu
          
      - name: Set execute permissions on gradlew
        run: chmod +x ./gradlew
        
      - name: Run Register User Negative Without Password Test
        run: ./gradlew test --tests ApiTest#negativeTestRegisterUserWithoutPassword
        
  test_get_user_positive:
    runs-on: ubuntu-latest
    needs: build  # Зависит от успешного выполнения 'register-user-tests'

    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Setup Java JDK
        uses: actions/setup-java@v4.6.0
        with:
          java-version: 22
          distribution: zulu
      - name: Set execute permissions on gradlew
        run: chmod +x ./gradlew
          
      - name: Run Get User Positive Test
        run: ./gradlew test --tests ApiTest#testGetUserPositive

  update-user-tests:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Setup Java JDK
        uses: actions/setup-java@v4.6.0
        with:
          java-version: 22
          distribution: zulu
      - name: Set execute permissions on gradlew
        run: chmod +x ./gradlew
          
      - name: Run Update User tests
        run: ./gradlew TestUpdateUser

  delete-user-tests:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Setup Java JDK
        uses: actions/setup-java@v4.6.0
        with:
          java-version: 22
          distribution: zulu

      - name: Set execute permissions on gradlew
        run: chmod +x ./gradlew
          
      - name: Run Delete User tests
        run: ./gradlew TestDeleteUser
      
