name: ApiTest
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Install deps
        run: npm ci
        
      - name: Build
        run: npm run build
      
