name: ApiTest
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Setup Java JDK
        uses: actions/setup-java@v4.6.0
        with:
          java-version: 22
          distribution: zulu
        
      - name: Set up Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

     # - name: Set up Docker
       # uses: docker/setup-buildx-action@v2

     # - name: Build Docker image
      #  run: docker build -t api-test .

     # - name: Run tests in Docker
     #   run: docker run --rm api-test

  test_register_user:
    runs-on: ubuntu-latest
    needs: build     
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
          
      - name: Set execute permissions on gradlew
        run: chmod +x ./gradlew
          
      - name: Run Register User tests
        run: ./gradlew TestRegisterUser
        
  test_get_user:
    runs-on: ubuntu-latest
    needs: build 

    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: Set execute permissions on gradlew
        run: chmod +x ./gradlew
          
      - name: Run Get User tests
        run: ./gradlew TestGetUser

  test_update_user:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: Set execute permissions on gradlew
        run: chmod +x ./gradlew
          
      - name: Run Update User tests
        run: ./gradlew TestUpdateUser

  test_delete_user:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: Set execute permissions on gradlew
        run: chmod +x ./gradlew
          
      - name: Run Delete User tests
        run: ./gradlew TestDeleteUser
        
  api_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: Set execute permissions on gradlew
        run: chmod +x ./gradlew
      - name: Run All Tagged Tests
        run: ./gradlew testAll
      - name: Prepare Allure Results
        run: mkdir -p build/allure-results

  allure_report:
    runs-on: ubuntu-latest
    needs: api_test
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build Allure Report
        uses: simple-elf/allure-report-action@v1.7
        with:
          gh_pages: main
          allure_history: allure-history
          allure_results: build/allure-results
